-- Run in the selected Supabase project. Backend secret key only; no browser access.
create table if not exists public.raft_incidents (
  id text primary key,
  question text not null,
  situation text not null default '',
  diagnosis text not null default '',
  actions jsonb not null default '[]'::jsonb,
  domain text not null default 'UNKNOWN',
  status text not null default 'new',
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null
);
create table if not exists public.raft_events (
  id bigint generated by default as identity primary key,
  incident_id text not null,
  type text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);
create table if not exists public.raft_faq (
  id bigint generated by default as identity primary key,
  signature text not null unique,
  question text not null,
  answer text not null,
  updated_at timestamptz not null
);
create index if not exists raft_incidents_status_idx on public.raft_incidents (status, updated_at desc);
create index if not exists raft_events_incident_idx on public.raft_events (incident_id, id);
alter table public.raft_incidents enable row level security;
alter table public.raft_events enable row level security;
alter table public.raft_faq enable row level security;
revoke all on public.raft_incidents, public.raft_events, public.raft_faq from anon, authenticated;
grant select, insert, update on public.raft_incidents, public.raft_events, public.raft_faq to service_role;
grant usage, select on all sequences in schema public to service_role;
